const API='https://api.telegram.org/bot';
const enc=new TextEncoder();
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store'}});
async function telegram(env,method,body){const r=await fetch(`${API}${env.BOT_TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return r.json()}
function hex(buf){return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function hmac(key,data,rawKey=false){const k=await crypto.subtle.importKey('raw',rawKey?key:enc.encode(key),{name:'HMAC',hash:'SHA-256'},false,['sign']);return crypto.subtle.sign('HMAC',k,enc.encode(data))}
async function auth(request,env){const raw=request.headers.get('X-Telegram-Init-Data')||'';if(!raw)return null;const p=new URLSearchParams(raw),hash=p.get('hash');if(!hash)return null;p.delete('hash');p.delete('signature');const check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');const secret=await hmac('WebAppData',env.BOT_TOKEN);const calc=hex(await hmac(secret,check,true));if(calc!==hash)return null;const authDate=Number(p.get('auth_date')||0);if(!authDate||Math.abs(Date.now()/1000-authDate)>86400)return null;try{const user=JSON.parse(p.get('user')||'{}');return {...user,isOwner:String(user.id)===String(env.OWNER_ID)}}catch{return null}}
async function send(env,chatId,text,reply_markup){return telegram(env,'sendMessage',{chat_id:chatId,text,reply_markup})}
function appButton(request){return {inline_keyboard:[[{text:'📱 فتح مكتبة المستهدفين',web_app:{url:new URL(request.url).origin}}]]}}
async function listTargets(env){const {results=[]}=await env.DB.prepare(`SELECT t.*, (SELECT COUNT(*) FROM target_photos p WHERE p.target_id=t.id) photo_count FROM targets t ORDER BY t.updated_at DESC,t.id DESC`).all();return results}
async function apiRoute(request,env,url){const user=await auth(request,env);if(!user)return json({error:'افتح التطبيق من داخل بوت Telegram.'},401);const parts=url.pathname.split('/').filter(Boolean);if(request.method==='GET'&&url.pathname==='/api/me')return json({user:{id:user.id,first_name:user.first_name||'',username:user.username||''},isOwner:user.isOwner});if(request.method==='GET'&&url.pathname==='/api/targets'){const targets=await listTargets(env);return json({targets,total:targets.length,isOwner:user.isOwner});}
 if(request.method==='GET'&&parts[1]==='targets'&&parts[2]){const id=Number(parts[2]);const row=await env.DB.prepare(`SELECT t.*, (SELECT COUNT(*) FROM target_photos p WHERE p.target_id=t.id) photo_count FROM targets t WHERE t.id=?`).bind(id).first();if(!row)return json({error:'غير موجود'},404);const {results:photos=[]}=await env.DB.prepare('SELECT id,file_id FROM target_photos WHERE target_id=? ORDER BY id').bind(id).all();return json({...row,photos});}
 if(request.method==='POST'&&url.pathname==='/api/targets'){if(!user.isOwner)return json({error:'غير مصرح'},403);const d=await request.json();const name=String(d.name||'').trim(),city=String(d.city||'').trim(),notes=String(d.notes||'').trim();const links=Array.isArray(d.links)?d.links.map(x=>String(x).trim()).filter(Boolean).slice(0,20):[];if(!name)return json({error:'اسم المحل مطلوب'},400);const r=await env.DB.prepare('INSERT INTO targets (name,city,url,notes,status,updated_at) VALUES (?,?,?,?,?,CURRENT_TIMESTAMP) RETURNING id').bind(name,city,JSON.stringify(links),notes,'new').first();return json({ok:true,id:r.id});}
 if(request.method==='PUT'&&parts[1]==='targets'&&parts[2]){if(!user.isOwner)return json({error:'غير مصرح'},403);const id=Number(parts[2]),d=await request.json();const links=Array.isArray(d.links)?d.links.map(x=>String(x).trim()).filter(Boolean).slice(0,20):[];await env.DB.prepare('UPDATE targets SET name=?,city=?,url=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(String(d.name||'').trim(),String(d.city||'').trim(),JSON.stringify(links),String(d.notes||'').trim(),id).run();return json({ok:true});}
 if(request.method==='DELETE'&&parts[1]==='targets'&&parts[2]){if(!user.isOwner)return json({error:'غير مصرح'},403);const id=Number(parts[2]);await env.DB.prepare('DELETE FROM target_photos WHERE target_id=?').bind(id).run();await env.DB.prepare('DELETE FROM targets WHERE id=?').bind(id).run();return json({ok:true});}
 return json({error:'Not found'},404)}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return apiRoute(request,env,url);if(request.method==='GET'&&url.pathname==='/setup-webhook'){const data=await telegram(env,'setWebhook',{url:`${url.origin}/telegram`,secret_token:env.WEBHOOK_SECRET,allowed_updates:['message'],drop_pending_updates:true});return new Response(data.ok?'✅ Telegram webhook connected.':data.description,{status:data.ok?200:502})}if(request.method==='POST'&&url.pathname==='/telegram'){if(env.WEBHOOK_SECRET&&request.headers.get('X-Telegram-Bot-Api-Secret-Token')!==env.WEBHOOK_SECRET)return new Response('Unauthorized',{status:401});const x=await request.json();if(x.message?.text==='/start')await send(env,x.message.chat.id,'🎯 مكتبة المستهدفين\n\nابحث، تصفح وأدر المحلات من تطبيق واحد داخل Telegram.',appButton(request));return new Response('ok')}return env.ASSETS.fetch(request)}};