const API='https://api.telegram.org/bot';
const enc=new TextEncoder();
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store'}});
async function telegram(env,method,body){const r=await fetch(`${API}${env.BOT_TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return r.json()}
function hex(buf){return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function hmacSign(keyBytes,data){const k=await crypto.subtle.importKey('raw',keyBytes,{name:'HMAC',hash:'SHA-256'},false,['sign']);return crypto.subtle.sign('HMAC',k,enc.encode(data))}
async function auth(request,env){const raw=request.headers.get('X-Telegram-Init-Data')||'';if(!raw||!env.BOT_TOKEN)return null;const p=new URLSearchParams(raw),hash=p.get('hash');if(!hash)return null;p.delete('hash');p.delete('signature');const check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');const secret=await hmacSign(enc.encode('WebAppData'),env.BOT_TOKEN);const calc=hex(await hmacSign(new Uint8Array(secret),check));if(calc.toLowerCase()!==hash.toLowerCase())return null;const authDate=Number(p.get('auth_date')||0);if(!authDate||Date.now()/1000-authDate>86400||authDate>Date.now()/1000+300)return null;try{const user=JSON.parse(p.get('user')||'{}');if(!user.id)return null;return {...user,isOwner:String(user.id)===String(env.OWNER_ID)}}catch{return null}}
async function send(env,chatId,text,reply_markup){return telegram(env,'sendMessage',{chat_id:chatId,text,reply_markup})}
function appButton(request){return {inline_keyboard:[[{text:'📱 فتح مكتبة المستهدفين',web_app:{url:new URL(request.url).origin}}]]}}
async function listTargets(env){const {results=[]}=await env.DB.prepare(`SELECT t.*, (SELECT COUNT(*) FROM target_photos p WHERE p.target_id=t.id) photo_count,(SELECT file_id FROM target_photos p WHERE p.target_id=t.id ORDER BY p.id LIMIT 1) cover_key FROM targets t ORDER BY t.updated_at DESC,t.id DESC`).all();return results}
async function apiRoute(request,env,url){const user=await auth(request,env);if(!user)return json({error:'تعذر التحقق من جلسة Telegram. أغلق التطبيق وافتحه من زر البوت مرة أخرى.'},401);const parts=url.pathname.split('/').filter(Boolean);
 if(request.method==='GET'&&url.pathname==='/api/me')return json({user:{id:user.id,first_name:user.first_name||'',username:user.username||''},isOwner:user.isOwner});
 if(request.method==='GET'&&url.pathname==='/api/targets'){const targets=await listTargets(env);return json({targets,total:targets.length,isOwner:user.isOwner});}
 if(request.method==='GET'&&parts[1]==='targets'&&parts[2]){const id=Number(parts[2]);const row=await env.DB.prepare(`SELECT t.*, (SELECT COUNT(*) FROM target_photos p WHERE p.target_id=t.id) photo_count FROM targets t WHERE t.id=?`).bind(id).first();if(!row)return json({error:'غير موجود'},404);const {results:photos=[]}=await env.DB.prepare('SELECT id,file_id FROM target_photos WHERE target_id=? ORDER BY id').bind(id).all();return json({...row,photos});}
 if(request.method==='POST'&&url.pathname==='/api/targets'){if(!user.isOwner)return json({error:'غير مصرح'},403);const d=await request.json();const name=String(d.name||'').trim(),city=String(d.city||'').trim(),notes=String(d.notes||'').trim();const links=Array.isArray(d.links)?d.links.map(x=>String(x).trim()).filter(Boolean).slice(0,20):[];if(!name)return json({error:'اسم المحل مطلوب'},400);const r=await env.DB.prepare('INSERT INTO targets (name,city,url,notes,status,updated_at) VALUES (?,?,?,?,?,CURRENT_TIMESTAMP) RETURNING id').bind(name,city,JSON.stringify(links),notes,'new').first();return json({ok:true,id:r.id});}
 if(request.method==='PUT'&&parts[1]==='targets'&&parts[2]){if(!user.isOwner)return json({error:'غير مصرح'},403);const id=Number(parts[2]),d=await request.json();const links=Array.isArray(d.links)?d.links.map(x=>String(x).trim()).filter(Boolean).slice(0,20):[];await env.DB.prepare('UPDATE targets SET name=?,city=?,url=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(String(d.name||'').trim(),String(d.city||'').trim(),JSON.stringify(links),String(d.notes||'').trim(),id).run();return json({ok:true});}
 if(request.method==='DELETE'&&parts[1]==='targets'&&parts[2]){if(!user.isOwner)return json({error:'غير مصرح'},403);const id=Number(parts[2]);const {results:photos=[]}=await env.DB.prepare('SELECT file_id FROM target_photos WHERE target_id=?').bind(id).all();for(const p of photos){if(String(p.file_id).startsWith('r2:'))await env.PHOTOS.delete(String(p.file_id).slice(3));}await env.DB.prepare('DELETE FROM target_photos WHERE target_id=?').bind(id).run();await env.DB.prepare('DELETE FROM targets WHERE id=?').bind(id).run();return json({ok:true});}
 if(request.method==='POST'&&parts[1]==='targets'&&parts[2]&&parts[3]==='photos'){if(!user.isOwner)return json({error:'غير مصرح'},403);const id=Number(parts[2]);const exists=await env.DB.prepare('SELECT id FROM targets WHERE id=?').bind(id).first();if(!exists)return json({error:'المستهدف غير موجود'},404);const form=await request.formData();const files=form.getAll('photos').filter(x=>x&&typeof x.arrayBuffer==='function').slice(0,12);if(!files.length)return json({error:'اختر صورة واحدة على الأقل'},400);const count=await env.DB.prepare('SELECT COUNT(*) c FROM target_photos WHERE target_id=?').bind(id).first();if(Number(count?.c||0)+files.length>20)return json({error:'الحد الأعلى 20 صورة للمحل'},400);const uploaded=[];for(const file of files){if(!String(file.type||'').startsWith('image/'))continue;if(file.size>8*1024*1024)continue;const ext=(file.name?.split('.').pop()||'jpg').replace(/[^a-zA-Z0-9]/g,'').slice(0,5)||'jpg';const key=`targets/${id}/${crypto.randomUUID()}.${ext}`;await env.PHOTOS.put(key,file.stream(),{httpMetadata:{contentType:file.type||'image/jpeg',cacheControl:'public, max-age=31536000, immutable'}});const r=await env.DB.prepare('INSERT INTO target_photos (target_id,file_id) VALUES (?,?) RETURNING id').bind(id,`r2:${key}`).first();uploaded.push({id:r.id,url:`/media/${encodeURIComponent(key)}`});}await env.DB.prepare('UPDATE targets SET updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(id).run();return json({ok:true,photos:uploaded});}
 if(request.method==='DELETE'&&parts[1]==='photos'&&parts[2]){if(!user.isOwner)return json({error:'غير مصرح'},403);const pid=Number(parts[2]);const p=await env.DB.prepare('SELECT file_id,target_id FROM target_photos WHERE id=?').bind(pid).first();if(!p)return json({error:'الصورة غير موجودة'},404);if(String(p.file_id).startsWith('r2:'))await env.PHOTOS.delete(String(p.file_id).slice(3));await env.DB.prepare('DELETE FROM target_photos WHERE id=?').bind(pid).run();await env.DB.prepare('UPDATE targets SET updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(p.target_id).run();return json({ok:true});}
 return json({error:'Not found'},404)}
async function mediaRoute(request,env,url){const key=decodeURIComponent(url.pathname.slice('/media/'.length));if(!key||key.includes('..'))return new Response('Not found',{status:404});const obj=await env.PHOTOS.get(key);if(!obj)return new Response('Not found',{status:404});const h=new Headers();obj.writeHttpMetadata(h);h.set('etag',obj.httpEtag);h.set('cache-control','public, max-age=31536000, immutable');return new Response(obj.body,{headers:h})}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return apiRoute(request,env,url);if(request.method==='GET'&&url.pathname.startsWith('/media/'))return mediaRoute(request,env,url);if(request.method==='GET'&&url.pathname==='/setup-webhook'){const data=await telegram(env,'setWebhook',{url:`${url.origin}/telegram`,secret_token:env.WEBHOOK_SECRET,allowed_updates:['message'],drop_pending_updates:true});return new Response(data.ok?'✅ Telegram webhook connected.':data.description,{status:data.ok?200:502})}if(request.method==='POST'&&url.pathname==='/telegram'){if(env.WEBHOOK_SECRET&&request.headers.get('X-Telegram-Bot-Api-Secret-Token')!==env.WEBHOOK_SECRET)return new Response('Unauthorized',{status:401});const x=await request.json();if(x.message?.text==='/start')await send(env,x.message.chat.id,'🎯 مكتبة المستهدفين\n\nابحث، تصفح وأدر المحلات من تطبيق واحد داخل Telegram.',appButton(request));return new Response('ok')}return env.ASSETS.fetch(request)}};